server:
    port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identityserver_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      connection-timeout: 3000000
      connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true

thymeleaf:
  prefix: classpath:/templates/

logging:
  level:
   root: info

security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT Example Realm

jwt.jks.keypass: keypass

spring.security.oauth2.clientId: 008fec3d-c125-409e-9f8d-ef7724ec21df
spring.security.oauth2.clientSecret: 222
spring.security.oauth2.authorization.check-token-access: http://localhost:8080/oauth/check_token
spring.security.oauth2.host: http://localhost:8080
spring.security.oauth2.resourceId: system


